name: Rubika Downloader Bot

on:
  schedule:
    - cron: '*/60 * * * *'
  workflow_dispatch:

jobs:
  bot:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -U pyrubi requests

      - name: Run bot
        env:
          ACCOUNT_JSON: ${{ secrets.ACCOUNT_JSON }}
        run: python download_bot.py
